AllCops:
  Include:
    - '**/*.rb'
  Exclude:
    - 'bin/*'
    - '*.gemspec'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*_spec.rb'

Style/FileName:
  Exclude:
    - '**/Rakefile'
    - '**/Gemfile'
